### PR TITLE
binlogName, binlogNextPos read from Zongji, pass to options

### PR DESCRIPTION
**Pull request by numtel**
* Allows graceful restarting
  https://gist.github.com/numtel/5b37b2a7f47b380c1a099596c6f3db2f
* Thank you @sirhanshafahath for your help with
  https://github.com/nevill/zongji/pull/14

### CODE REVIEW

**Comment by numtel** [comment]
There's now a test to make sure that ZongJi can be resumed by a different instance after stopping without losing order of binlog events.

Let's release 0.4.3 with this PR, [this bug fix](https://github.com/nevill/zongji/pull/46) and [this one](https://github.com/nevill/zongji/pull/50) as long as its reproducible and there's a test written.

**Comment by prdn** [comment]
This one is really nice to have

**Comment by numtel** [comment]
@nevill Do you have any concerns/comments? If not, I'll merge these 3 PRs so that master is ready for releasing 0.4.3.

**Comment by snolangps** [comment]
@numtel how does this have the `binlogNextPos` and pass to the options?

**Pull request merged**
