### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by dazzyon**
Edit tableInfoQueryTemplate query, so it doesn't have double quotes inside the query (throws an error).

### CODE REVIEW

**Comment by numtel** [comment]
What error is thrown without this patch?

**Comment by dazzyon** [comment]
Without the patch i get this error when this query is executed:

```
C:\Users\Hugo\AppData\Local\.meteor\packages\numtel_mysql\1.0.6\npm\node_modules\mysql\lib\protocol\Parser.js:77
throw err; // Rethrow non-MySQL errors
         ^
Error: ER_BAD_FIELD_ERROR: Unknown column 'crm' in 'where clause'
at Query.Sequence._packetToError (C:\Users\Hugo\AppData\Local\.meteor\packages\numtel_mysql\1.0.6\npm\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14)
```
I get a simular error when i execute the query with a MySQL client.

`SQL Error (1146): Table 'crm.columns' doesn't exist`

MySQL version: 5.1.41

**Comment by numtel** [comment]
OK,

**Comment by numtel** [comment]
W

**Comment by numtel** [comment]
Ugh, my phone had water on the screen

Anyways.... What's the full table and column name causing that error? There will need to be a test case written that fails without this patch.

**Comment by dazzyon** [comment]
Because the query also returns an error in a MySQL client i think it might be a combination of using double quotes and a MySQL DB setting.

In the documentation i found the following setting:

If the ANSI_QUOTES SQL mode is enabled, string literals can be quoted only within single quotation marks because a string quoted within double quotation marks is interpreted as an identifier.

Tomorrow i can check if this is enabled and give more details if the error still excists when i disable this mode.

**Comment by dazzyon** [comment]
I can confirm the ANSI_QUOTES mode was enabled.

**Comment by numtel** [comment]
It makes sense now that I look at [the documentation for the ANSI_QUOTES setting](https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_ansi_quotes).

I have created a new pull request with an updated commit message for your commit as well as a commit that fixes the test suite so that the tests are run in both the default SQL mode and in "ANSI_QUOTES" mode. https://github.com/nevill/zongji/pull/57

**Pull request closed without merging**
