### PR TITLE
Implement IntVar event

### PR DESCRIPTION
**Pull request by mrichards42**
This event comes directly before a Query event that uses either an auto-increment id or LAST_INSERT_ID()

https://dev.mysql.com/doc/internals/en/intvar-event.html

### CODE REVIEW

**Comment by numtel** [comment]
There will need to be a test case for this. What queries could be run to emit an `IntVar` event?

**Comment by mrichards42** [comment]
Sure thing, I can write up a test for this.

This series of statements should produce both types of IntVar events.  Correct me if I'm wrong, but it looks like test/events.js is only testing the row-based replication events? 

```
CREATE TABLE test (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  col INT
);

-- Event: IntVar type=INSERT_ID value=1
-- Event: Query
INSERT INTO test (col) VALUES (100);

-- Event: IntVar type=LAST_INSERT_ID value=1
-- Event: IntVar type=INSERT_ID value=2
-- Event: Query
INSERT INTO test (col) VALUES (LAST_INSERT_ID());
```

**Comment by numtel** [comment]
Ok I don't seem to get any `intvar` events at all. Is there anything I'm missing?

A case for test/events.js:
```js
  testIntvar: function(test){
    var testTable = 'intvar_test';
    querySequence(conn.db, [
      'DROP TABLE IF EXISTS ' + conn.escId(testTable),
    ], function(error, results){
      if(error) console.error(error);
      // Start second ZongJi instance
      var zongji = new ZongJi(settings.connection);
      var events = [];

      zongji.on('binlog', function(event) {
        event.dump();
        events.push(event);
        // OR some condition that actually makes the test complete
        if(events.length>20) {
          console.log(events);
          zongji.stop();
          test.done();
        }
      });

      zongji.start({
        startAtEnd: true,
        serverId: 12, // Second instance must not use same server ID
        includeEvents: ['intvar', 'query', 'tablemap', 'writerows', 'xid']
      });

      // Give enough time to initialize
      setTimeout(function(){
        querySequence(conn.db, [
          'CREATE TABLE ' + conn.escId(testTable) + ' (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY , col INT)',
          'INSERT INTO ' + conn.escId(testTable) + ' (col) VALUES (10)',
          'INSERT INTO ' + conn.escId(testTable) + ' (col) VALUES (LAST_INSERT_ID())',
        ], function(error, results){
          if(error) console.error(error);
        });
      }, 200);
    });
  },
```

**Comment by mrichards42** [comment]
I edited your test and added it to the PR.  The issue is that `intvar` events are only emitted when using statement-based replication.  I went ahead and added `SET SESSION binlog_format=[ROW|STATEMENT]` before each test as well.

**Comment by mrichards42** [comment]
Ah, my bad -- I was running the events.js test on its own, so adding `SET SESSION binlog_format=STATEMENT` broke all the following tests.  Also, curiously on my setup I was getting an extra `Query BEGIN` event before each IntVar/Query combo, so even the test that passed on my machine breaks travis.  I'll get back to this when I have a sec later today.

**Comment by mrichards42** [comment]
OK, I just went ahead and set statement-based only for the intvar test since it looks like the rest of the tests expect row-based.  Looks like the travis build is happy.

**Comment by numtel** [comment]
Nice, that seems to make it work. I didn't realize that it was possible to change the binlog mode so easily from the client. Give me a day to try to come up with a solution to [this issue](https://github.com/nevill/zongji/issues/59) and then I'll get this into master for a new release.

**Pull request merged**
