### PR TITLE
metadata for time with fractional part

### PR DESCRIPTION
**Pull request by madeuz**
according to https://docs.oracle.com/cd/E17952_01/mysql-5.6-relnotes-en/news-5-6-4.html
"In the MYSQL_FIELD column metadata structure, the decimals member indicates the fractional seconds precision for TIME, DATETIME, and TIMESTAMP columns."
it is added here: https://github.com/mysql/mysql-server/blob/f964f6b37337b98d467c1e9fb7914c1655a08e84/sql/field.h#L2685
for older versions it also works because format is recognized as TIMESTAMP and DATETIME when in newer TIMESTAMP2 and DATETIME2
tested in 5.5.40, 5.6.41 and 5.7.5-m15

### CODE REVIEW

**Comment by numtel** [comment]
Can you add a test that would fail without this patch?

**Comment by numtel** [comment]
Also, with this would it be possible to update the way the number of decimals is currently being read from the column type string?

https://github.com/nevill/zongji/blob/master/lib/common.js#L344
```javascript
  var fractionPrecision = parseTypeDefIntArg(columnSchema.COLUMN_TYPE);
```

https://github.com/nevill/zongji/blob/master/lib/common.js#L88-94
```javascript
// @param {string} type - ex. 'time(4)'
// @return {int} - ex. 4
var parseTypeDefIntArg = function(type){
  var start = type.indexOf('(') + 1;
  if(start === 0) return undefined;
  return parseInt(type.substr(start, type.length - start - 1), 10);
};
```

**Comment by madeuz** [comment]
There was a bug if in table schema was a DATETIME column and next DECIMAL(X,Y) column. It was incorrectly reading X or Y and incorrectly calculating buffer size, which was causing crash: 
RangeError: Trying to access beyond buffer length

I will add a test case later.

**Comment by numtel** [comment]
Ah ok, that does produce an error :smile: 

Here's a test case that you can place at the end of `test/types.js`

```javascript
defineTypeTest('datetime_then_decimal', [
  'DATETIME(3) NULL',
  'DECIMAL(30, 10) NULL'
], [
  ['"1000-01-01 00:00:00.123"', 10.10],
  ['"9999-12-31 23:59:59.001"', -123.45],
  ['"2014-12-27 01:07:08.053"', 12345.123]
], '5.6.4');
```

**Comment by madeuz** [comment]
Thanks, I added this test.

On the further question I'm not really sure how MySQL interpret temporal types. There is a condition: 
https://github.com/mysql/mysql-server/blob/f964f6b37337b98d467c1e9fb7914c1655a08e84/sql/field.h#L2628
Which I don't really know when applies.

Otherside, it should always write 1 byte metadata for datetime or timestmpe column with fractional part (or even without - meaning 000...) in vesion > 5.6.4, so it be would always possible to calculate the number of decimals.

**Comment by numtel** [comment]
@madeuz Cool, I went ahead and merged this. The same metadata applies to the TIME2 data type

https://github.com/mysql/mysql-server/blob/f964f6b37337b98d467c1e9fb7914c1655a08e84/sql/field.h#L3061

So in [the latest commit](https://github.com/nevill/zongji/commit/e1218dcb77d82233450740c820eed6c19b0c58fd) I just made after merging, I have added that to `binlog_event.js` as well as made the value parser in `common.js` read from the metadata instead of parsing the column type string.

As far as I can tell, the conditional you linked to has to do with that class abstracting the differences between DATETIME and TIMESTAMP from DATETIME2 and TIMESTAMP2 (the fractional part) because MySQL >= 5.6.4 still needs to interface with databases created with older versions. Because there are separate types and we handle them differently it should pose no problem.

@nevill Can you release version 0.3.2?

**Comment by nevill** [comment]
0.3.2 is out! Thank you guys :+1:

**Pull request merged**
